config/routes.rb
Rg::Application.routes.draw do

  resources :menu_blocks,
            :only => :create,
            :as => :menu_blocks,
            :controller => 'menu_blocks' do
    collection do
      get :thank_you
    end
  end

  resources :menu_blocks, :only => [:index, :show, :new]
    scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
      resources :menu_blocks, :except => :show do
        collection do
        post :update_positions
      end
    end
  end

  resources :enrollments,
            :only => :create,
            :as => :enrollments,
            :controller => 'enrollments' do
    collection do
      get :thank_you_for_enrolling
    end
  end

  resources :enrollments, :only => [:index, :show, :new]
    scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
      resources :enrollments, :except => :show do
        collection do
        post :update_positions
      end
    end
  end

  resources :partners,
            :only => :create,
            :as => :partners,
            :controller => 'partners' do
    collection do
      get :thank_you_for_enrolling
    end
  end

  resources :partners, :only => [:index, :show, :new]
    scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
      resources :partners, :except => :show do
        collection do
        post :update_positions
      end
    end
  end

end

app/models/menu_block.rb
class MenuBlock < ActiveRecord::Base

  acts_as_indexed :fields => [:name, :title]

  validates :name, :presence => true, :uniqueness => true

  has_many  :menu_pages, :dependent => :destroy
  has_many  :pages, :through => :menu_pages


  def page_ids
     self.menu_pages.map(&:page_id)
  end

  def page_ids=(new_ids)
     new_ids = (new_ids || []).reject(&:blank?)
     old_ids = self.page_ids

     #self.transaction do
       MenuPage.destroy_all({ :page_id => old_ids, :menu_block_id => self.id })
       new_ids.each do |page_id|
         self.menu_pages.create!(:page_id => page_id)
       end
     #end
  end

end

app/controllers/admin/menu_blocks_controller.rb
module Admin
  class MenuBlocksController < Admin::BaseController

    crudify :menu_block,
            :title_attribute => 'name', :xhr_paging => true

    def create
      puts params

      @menu_block = MenuBlock.new(params[:menu_block])

       if @menu_block.save
         @menu_block.page_ids=params[:menu_pages]? params[:menu_pages].collect {|x| x.to_i } : []
         flash[:notice] = t('menu_block.update_ok')
         redirect_to admin_menu_blocks_path
       else
         respond_to do |format|
           format.html  { render :action => "edit" }
           format.json  { render :json => @menu_block.errors }
         end
       end

    end


    def update
      puts params

      @menu_block = MenuBlock.find(params[:id])

       if @menu_block.update_attributes(params[:menu_block])
         @menu_block.page_ids=params[:menu_pages]? params[:menu_pages].collect {|x| x.to_i } : []
         flash[:notice] = t('menu_block.update_ok')
         redirect_to admin_menu_blocks_path
       else
         respond_to do |format|
           format.html  { render :action => "edit" }
           format.json  { render :json => @menu_block.errors }
         end
       end

    end

  end
end

app/controllers/menu_blocks_controller.rb
class MenuBlocksController < ApplicationController

  before_filter :find_page, :only => [:create, :new]

  before_filter :find_all_menu_blocks

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @menu_block in the line below:
    present(@page)
  end

  def show
    @menu_block = MenuBlock.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @menu_block in the line below:
    present(@page)
  end

  def new
    @menu_block =MenuBlock.new
    present(@page)
  end

  def create
    @menu_block =MenuBlock.new(params[:menu_block])
    present(@page)
  end

protected

  def find_all_menu_blocks
    @menu_blocks = MenuBlock.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/menu_blocks").first
  end

end

app/views/admin/menu_blocks/_actions.html.erb
<ul>
  <% if Admin::MenuBlocksController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_menu_blocks_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_menu_block_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::MenuBlocksController.sortable? and MenuBlock.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Menu Blocks"),
                 admin_menu_blocks_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Menu Blocks"),
                 admin_menu_blocks_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/menu_blocks/_form.html.erb
  <%= stylesheet_link_tag "application.css" %>

  <%= stylesheet_link_tag "ui.multiselect.css" %>
  <%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css" %>

<% content_for :javascripts do %>
  <%= javascript_include_tag('plugins/localisation/jquery.localisation-min', 'plugins/scrollTo/jquery.scrollTo-min', 'ui.multiselect', 'themeswitchertool') %>
<% end %>


<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
        $.localise('ui-multiselect', {/*language: 'en',*/ path: 'locale/'});
        $(".multiselect").multiselect();
        $('#switcher').themeswitcher();
    });
  </script>
<% end %>

  <%
      page_ids=[]
      @menu_block.menu_pages.each{ |val| page_ids << val.page_id }
      all_page_ids_selected={}
      all_page_ids_unselected={}
      tmp=all_children_for_id(nil,0)

      page_ids.each {|val| all_page_ids_selected[val] = tmp[val]; all_page_ids_selected[val][:selected] = true }

      all_page_ids_unselected=tmp.select{|key,val| !page_ids.include?(key) }

      all_page_ids=all_page_ids_selected.merge( all_page_ids_unselected )

  %>


<%= form_for [:admin, @menu_block] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @menu_block,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title  -%>
  </div>
  
  <div class='field'>
    <%= f.label :deletable -%>
    <%= f.text_field :deletable  -%>
  </div>

  <div class='field'>
    <%= f.label :pages -%>
      <select id="menu_block_page_id" class="multiselect" multiple="multiple" name="menu_pages[]">
    <%  all_page_ids.each_value do |val| %>
        <option value="<%= val[:id] %>" <%= 'selected="selected"'.html_safe if val[:selected] %> ><%= '--'*val[:level] + ' ' + val[:title] %></option>
    <% end %>
      </select>


    <!-- <br><div id="switcher"></div> -->
  </div>

  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.menu_blocks.menu_block'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @menu_block.name)
              } %>
<% end -%>

app/views/admin/menu_blocks/_menu_block.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(menu_block) -%>">
  <span class='title'>
    <%= menu_block.name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%#= link_to refinery_icon_tag("application_go.png"), menu_block_path(menu_block),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_menu_block_path(menu_block),
         :title => t('.edit') %>
    <% if menu_block.deletable != 0 %>
    <%= link_to refinery_icon_tag("delete.png"), admin_menu_block_path(menu_block),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => menu_block.name),
        :method => :delete %>
     <% end %>
  </span>
</li>

app/views/admin/menu_blocks/_menu_blocks.html.erb
<%= will_paginate @menu_blocks %>
<%= render :partial => "sortable_list" %>

app/views/admin/menu_blocks/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @menu_blocks.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'menu_blocks' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/menu_blocks/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'menu_block', :collection => @menu_blocks %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/menu_blocks/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/menu_blocks/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::MenuBlocksController.sortable? and MenuBlock.count > 1 %>