config/routes.rb
Rg::Application.routes.draw do

  resources :menu_blocks,
            :only => :create,
            :as => :menu_blocks,
            :controller => 'menu_blocks' do
    collection do
      get :thank_you
    end
  end

  resources :menu_blocks, :only => [:index, :show, :new]
    scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
      resources :menu_blocks, :except => :show do
        collection do
        post :update_positions
      end
    end
  end

  resources :enrollments,
            :only => :create,
            :as => :enrollments,
            :controller => 'enrollments' do
    collection do
      get :thank_you_for_enrolling
    end
  end

  resources :enrollments, :only => [:index, :show, :new]
    scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
      resources :enrollments, :except => :show do
        collection do
        post :update_positions
      end
    end
  end

  resources :partners,
            :only => :create,
            :as => :partners,
            :controller => 'partners' do
    collection do
      get :thank_you_for_enrolling
    end
  end

  resources :partners, :only => [:index, :show, :new]
    scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
      resources :partners, :except => :show do
        collection do
        post :update_positions
      end
    end
  end

end

app/models/partner.rb
class Partner < ActiveRecord::Base

  acts_as_indexed :fields => [:name, :company, :position, :cooperation, :email, :phone]

  validates :name, :presence => true,
            :length => { :maximum => 255 }
  validates :company, :presence => true,
            :length => { :maximum => 255 }
  validates :email, :presence => true,
            :length => { :minimum => 6, :maximum => 255 },
            :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :phone, :presence => true,
            :length => { :maximum => 255 }

  
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  before_filter :find_page, :only => [:create, :new]
#  before_filter :find_page
  before_filter :find_all_partners

  def become_partner_thank_you
    @page = Page.find_by_link_url("/partners/become_partner_thank_you", :include => [:parts, :slugs])
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(params[:partner])

#    puts params[:partner]

    if @partner.save
      redirect_to become_partner_thank_you_partners_url
    else
      flash[:notice] = "Some error"
      render :action => 'new'
    end
  end


  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @partner in the line below:
    present(@page)
  end

  def show
    @partner = Partner.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @partner in the line below:
    present(@page)
  end

protected

  def find_all_partners
    @partners = Partner.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/partners").first
  end


end

app/views/partners/_error_messages.html.erb
<% if object.errors.any? %>
<div class="errorExplanation" id="errorExplanation">
  <p><%= t('.problems_in_following_fields') %>:</p>
  <ul>
  <% unless defined?(include_object_name) and include_object_name %>
    <% object.errors.each do |key, value| %>
      <li><%= value %></li>
    <% end %>
  <% else %>
    <% object.errors.full_messages.each do |value| %>
      <li><%= value %></li>
    <% end %>
  <% end %>
  </ul>
</div>
<% end %>

app/views/partners/_form.html.erb
<%= form_for @partner, :html => { :method => 'post' } do |f| -%>
    <%
       partner_form_of_cooperation =[]

       partner_form_of_cooperation=RefinerySetting.find_by_name( :partner_form_of_cooperation ).value[locale].each { |val| partner_form_of_cooperation << [val,val] }

    %>

    <%= render :partial => "error_messages", :locals => { :object => @partner, :include_object_name => true } %>

    <div class="form big">
        <div class="top"></div>
        <div class="bot"></div>

      <p>
        <%= f.label :name -%>
        <%= f.text_field :name, :class => 'larger widest'  -%>
      </p>

    <p>
        <%= f.label :company -%>
        <%= f.text_field :company  -%>
    </p>

    <p>
        <%= f.label :position -%>
        <%= f.text_field :position  -%>
    </p>

    <p>
        <%= f.label :cooperation, "Form of cooperation" -%>
        <%= f.select :cooperation, options_for_select(partner_form_of_cooperation, params[:cooperation]) -%>
        <%#= f.text_field :cooperation  -%>
    </p>

    <p>
        <%= f.label :email -%>
        <%= f.text_field :email  -%>
    </p>

    <p>
        <%= f.label :phone, "Phone number" -%>
        <%= f.text_field :phone  -%>
    </p>

   <%= content_tag :button, :type => :submit, :name => :commit do %>
   <% end %>

   </div>
<% end -%>

app/views/partners/become_partner_thank_you.html.erb
<%= render :partial => "/shared/content_page" %>

app/views/partners/index.html.erb
<% content_for :body_content_left do %>
  <ul id="partners">
    <% @partners.each do |partner| %>
      <li>
        <%= link_to partner.name, partner_path(partner) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/partners/new.html.erb
<%= render :partial => "form" %>

app/views/partners/show.html.erb
<% content_for :body_content_title do %>
  <%= @partner.name %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Name</h1>
    <p>
      <%=raw @partner.name %>
    </p>
  </section>
  <section>
    <h1>Company</h1>
    <p>
      <%=raw @partner.company %>
    </p>
  </section>
  <section>
    <h1>Position</h1>
    <p>
      <%=raw @partner.position %>
    </p>
  </section>
  <section>
    <h1>Cooperation</h1>
    <p>
      <%=raw @partner.cooperation %>
    </p>
  </section>
  <section>
    <h1>Email</h1>
    <p>
      <%=raw @partner.email %>
    </p>
  </section>
  <section>
    <h1>Phone</h1>
    <p>
      <%=raw @partner.phone %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="partners">
      <% @partners.each do |partner| %>
        <li>
          <%= link_to partner.name, partner_path(partner) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>